/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/Study'
import { Route as CreateRouteImport } from './routes/Create'
import { Route as IndexRouteImport } from './routes/index'

const StudyRoute = StudyRouteImport.update({
  id: '/Study',
  path: '/Study',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/Create',
  path: '/Create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Create': typeof CreateRoute
  '/Study': typeof StudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Create': typeof CreateRoute
  '/Study': typeof StudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Create': typeof CreateRoute
  '/Study': typeof StudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Create' | '/Study'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Create' | '/Study'
  id: '__root__' | '/' | '/Create' | '/Study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  StudyRoute: typeof StudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Study': {
      id: '/Study'
      path: '/Study'
      fullPath: '/Study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Create': {
      id: '/Create'
      path: '/Create'
      fullPath: '/Create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  StudyRoute: StudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
